modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="nebulithic_ascension_rewritten"
version="1.15.2-3.1.0beta1"
displayName="Nebulithic Ascension "
credits="ZapSplat- For sound effects, Blockbench- For block models"
displayURL="https://www.curseforge.com/minecraft/mc-mods/nebulithic-ascension"
authors="AJ"
description='''
Explore unimaginable places in faraway galaxies
'''

[[dependencies.nebulithic_ascension_rewritten]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




