modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="nebulithic_ascension_rewritten"
version="1.15.2-3.0.0beta1-git-"
displayName="Nebulithic Ascension "
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://www.curseforge.com/minecraft/mc-mods/nebulithic-ascension"
authors="AJ, MCreator"
description='''
Explore unimaginable places in faraway galaxies
'''

[[dependencies.nebulithic_ascension_rewritten]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




